"""
transpiler.py
=============
A tiny Python -> HLS C++ transpiler targeting the Pynq-Z2.

It takes a SINGLE Python function built from a small, well-defined subset of
the language and emits synthesizable HLS C++, including the AXI-Lite interface
pragmas needed to drive the block from the Zynq processing system (the ARM CPU).

It does NOT understand arbitrary Python. It walks the function's abstract
syntax tree (using Python's built-in `ast` module) and translates one language
construct at a time. Each construct has its own small handler, so ANY function
built out of the supported constructs transpiles -- you never hand-edit this
file per input. Anything outside the supported subset raises
`UnsupportedConstruct` with a clear message, so it never silently emits
broken C++.

--------------------------------------------------------------------------
SUPPORTED SUBSET (Tier 1)
--------------------------------------------------------------------------
  * exactly one top-level `def` and nothing else in the file/source
  * scalar arguments               -> all mapped to the fixed-point type
  * local variable assignment      x = expr
  * augmented assignment           x += expr        (also -= *= /=)
  * arithmetic                     +  -  *  /  and unary minus
  * comparisons                    <  <=  >  >=  ==  !=
  * boolean operators              and  or  not
  * if / elif / else
  * for i in range(...)            with CONSTANT integer bounds
                                   range(N), range(A,B), range(A,B,S)
  * return expr
  * numeric / boolean literals, variable names
  * pass, and a docstring on the function

--------------------------------------------------------------------------
NOT SUPPORTED (each raises a clear error instead of emitting bad C++)
--------------------------------------------------------------------------
  * while loops                    (unbounded -> not synthesizable as-is)
  * lists / dicts / tuples / sets / strings
  * function calls other than range()
  * multiple or nested function definitions; recursion
  * imports, classes, decorators, global/nonlocal
  * tuple unpacking / multiple assignment targets  (a, b = ...)
  * f-strings, comprehensions, lambdas, generators
  * ** (power), // (floor div), % (mod), bitwise operators
  * chained comparisons            (a < b < c)
  * range() with non-constant (variable) bounds

--------------------------------------------------------------------------
TYPE MODEL (deliberately simple)
--------------------------------------------------------------------------
  * every argument and every variable is ONE fixed-point type
    (default ap_fixed<16,6> = 16 total bits, 6 integer bits)
  * loop counters are plain `int`
  * the return type defaults to the same fixed-point type; override it to
    "int" for functions that return a 0/1 decision signal
  * we do NOT infer types -- that is a research-grade problem and out of scope
"""

import ast
import inspect
import textwrap


class UnsupportedConstruct(Exception):
    """Raised when the input Python uses something outside the Tier-1 subset."""
    pass


class HLSTranspiler(ast.NodeVisitor):
    def __init__(self, fixed_type="ap_fixed<16,6>", return_type=None):
        self.fixed_type = fixed_type
        self.return_type = return_type or fixed_type
        self.declared = set()      # variables already declared in the C++ output
        self.arg_names = []
        self.func_name = None
        self.lines = []
        self.indent = 1

    # ------------------------------------------------------------------ #
    # small helpers
    # ------------------------------------------------------------------ #
    def emit(self, text):
        self.lines.append("    " * self.indent + text)

    def _fail(self, node, what):
        line = getattr(node, "lineno", "?")
        raise UnsupportedConstruct(
            f"Unsupported Python construct: {what} (line {line}). "
            f"See the SUPPORTED SUBSET section in transpiler.py."
        )

    # ------------------------------------------------------------------ #
    # entry point
    # ------------------------------------------------------------------ #
    def transpile(self, source):
        source = textwrap.dedent(source)
        tree = ast.parse(source)
        funcs = [n for n in tree.body if isinstance(n, ast.FunctionDef)]
        if len(funcs) != 1 or len(tree.body) != 1:
            raise UnsupportedConstruct(
                "Input must be exactly one top-level function definition "
                "and nothing else."
            )
        self.lines = [
            "// ===== AUTO-GENERATED by transpiler.py -- do not edit by hand =====",
            '#include "ap_fixed.h"',
            "",
        ]
        self._emit_function(funcs[0])
        return "\n".join(self.lines), self._make_header()

    # ------------------------------------------------------------------ #
    # function
    # ------------------------------------------------------------------ #
    def _emit_function(self, node):
        if node.decorator_list:
            self._fail(node, "decorators")
        a = node.args
        if (a.vararg or a.kwarg or a.kwonlyargs or a.defaults
                or getattr(a, "posonlyargs", [])):
            self._fail(node, "*args / **kwargs / defaults / positional-only args")

        self.func_name = node.name
        self.arg_names = [arg.arg for arg in a.args]
        self.declared = set(self.arg_names)  # arguments are already "declared" as ports

        params = ", ".join(f"{self.fixed_type} {n}" for n in self.arg_names)
        self.lines.append(f"{self.return_type} {self.func_name}({params}) {{")

        # AXI-Lite interface: lets the PS write args / read result / start-stop
        for n in self.arg_names:
            self.emit(f"#pragma HLS INTERFACE s_axilite port={n} bundle=CONTROL")
        self.emit("#pragma HLS INTERFACE s_axilite port=return bundle=CONTROL")
        self.lines.append("")

        for stmt in node.body:
            self.visit(stmt)
        self.lines.append("}")

    # ------------------------------------------------------------------ #
    # statement visitors  (emit into self.lines)
    # ------------------------------------------------------------------ #
    def visit_Assign(self, node):
        if len(node.targets) != 1 or not isinstance(node.targets[0], ast.Name):
            self._fail(node, "multiple / tuple / non-simple assignment targets")
        name = node.targets[0].id
        value = self.expr(node.value)
        if name in self.declared:
            self.emit(f"{name} = {value};")
        else:
            self.declared.add(name)
            self.emit(f"{self.fixed_type} {name} = {value};")

    def visit_AugAssign(self, node):
        if not isinstance(node.target, ast.Name):
            self._fail(node, "augmented assignment to a non-variable")
        name = node.target.id
        if name not in self.declared:
            self._fail(node, f"'{name}' used with an augmented assignment before being assigned")
        self.emit(f"{name} {self._binop(node.op)}= {self.expr(node.value)};")

    def visit_Return(self, node):
        if node.value is None:
            self.emit("return;")
        else:
            self.emit(f"return {self.expr(node.value)};")

    def visit_If(self, node):
        self._emit_if(node, first=True)

    def _emit_if(self, node, first):
        kw = "if" if first else "} else if"
        self.emit(f"{kw} ({self.expr(node.test)}) {{")
        self.indent += 1
        for s in node.body:
            self.visit(s)
        self.indent -= 1
        if node.orelse:
            if len(node.orelse) == 1 and isinstance(node.orelse[0], ast.If):
                self._emit_if(node.orelse[0], first=False)   # elif
            else:
                self.emit("} else {")
                self.indent += 1
                for s in node.orelse:
                    self.visit(s)
                self.indent -= 1
                self.emit("}")
        else:
            self.emit("}")

    def visit_For(self, node):
        if node.orelse:
            self._fail(node, "for/else")
        if not isinstance(node.target, ast.Name):
            self._fail(node, "for loop with a non-simple target (e.g. unpacking)")
        it = node.iter
        if not (isinstance(it, ast.Call) and isinstance(it.func, ast.Name)
                and it.func.id == "range"):
            self._fail(node, "for loop that is not 'for x in range(...)'")
        if it.keywords:
            self._fail(node, "range() with keyword arguments")

        bounds = [self._const_int(arg) for arg in it.args]
        var = node.target.id
        if len(bounds) == 1:
            start, stop, step = 0, bounds[0], 1
        elif len(bounds) == 2:
            start, stop, step = bounds[0], bounds[1], 1
        elif len(bounds) == 3:
            start, stop, step = bounds
        else:
            self._fail(node, "range() with the wrong number of arguments")
        if step == 0:
            self._fail(node, "range() with a step of 0")

        cmp = "<" if step > 0 else ">"
        if step == 1:
            inc = f"{var}++"
        elif step == -1:
            inc = f"{var}--"
        else:
            inc = f"{var} += {step}"

        self.emit(f"for (int {var} = {start}; {var} {cmp} {stop}; {inc}) {{")
        self.indent += 1
        self.emit("#pragma HLS PIPELINE II=1")
        was_declared = var in self.declared
        self.declared.add(var)
        for s in node.body:
            self.visit(s)
        if not was_declared:
            self.declared.discard(var)
        self.indent -= 1
        self.emit("}")

    def _const_int(self, node):
        # range() bounds must be constant integer literals (allow -N via USub)
        if isinstance(node, ast.Constant) and isinstance(node.value, int) \
                and not isinstance(node.value, bool):
            return node.value
        if isinstance(node, ast.UnaryOp) and isinstance(node.op, ast.USub) \
                and isinstance(node.operand, ast.Constant) \
                and isinstance(node.operand.value, int):
            return -node.operand.value
        self._fail(node, "range() bound that is not a constant integer literal")

    def visit_Pass(self, node):
        pass  # nothing to emit

    def visit_Expr(self, node):
        # allow a docstring; reject any other bare expression (no hardware effect)
        if isinstance(node.value, ast.Constant) and isinstance(node.value.value, str):
            return
        self._fail(node, "bare expression statement")

    def generic_visit(self, node):
        # any statement without a visit_* handler above is unsupported
        self._fail(node, type(node).__name__)

    # ------------------------------------------------------------------ #
    # expression handlers  (return a C++ string)
    # ------------------------------------------------------------------ #
    def expr(self, node):
        handler = getattr(self, f"_e_{type(node).__name__}", None)
        if handler is None:
            self._fail(node, f"expression '{type(node).__name__}'")
        return handler(node)

    def _binop(self, op):
        table = {ast.Add: "+", ast.Sub: "-", ast.Mult: "*", ast.Div: "/"}
        if type(op) not in table:
            self._fail(op, f"arithmetic operator '{type(op).__name__}' (only + - * / supported)")
        return table[type(op)]

    def _e_BinOp(self, node):
        return f"({self.expr(node.left)} {self._binop(node.op)} {self.expr(node.right)})"

    def _e_UnaryOp(self, node):
        if isinstance(node.op, ast.USub):
            return f"(-{self.expr(node.operand)})"
        if isinstance(node.op, ast.UAdd):
            return f"(+{self.expr(node.operand)})"
        if isinstance(node.op, ast.Not):
            return f"(!{self.expr(node.operand)})"
        self._fail(node, f"unary operator '{type(node.op).__name__}'")

    def _e_Compare(self, node):
        if len(node.ops) != 1:
            self._fail(node, "chained comparison (e.g. a < b < c)")
        table = {ast.Lt: "<", ast.LtE: "<=", ast.Gt: ">", ast.GtE: ">=",
                 ast.Eq: "==", ast.NotEq: "!="}
        op = type(node.ops[0])
        if op not in table:
            self._fail(node, f"comparison '{op.__name__}'")
        return f"({self.expr(node.left)} {table[op]} {self.expr(node.comparators[0])})"

    def _e_BoolOp(self, node):
        glue = "&&" if isinstance(node.op, ast.And) else "||"
        return "(" + f" {glue} ".join(self.expr(v) for v in node.values) + ")"

    def _e_Name(self, node):
        return node.id

    def _e_Constant(self, node):
        v = node.value
        if isinstance(v, bool):
            return "true" if v else "false"
        if isinstance(v, int):
            return str(v)
        if isinstance(v, float):
            # cast float constants to the fixed type so precision is explicit
            return f"{self.fixed_type}({v})"
        self._fail(node, f"constant of type '{type(v).__name__}'")

    # ------------------------------------------------------------------ #
    # header
    # ------------------------------------------------------------------ #
    def _make_header(self):
        params = ", ".join(f"{self.fixed_type} {n}" for n in self.arg_names)
        guard = f"{self.func_name.upper()}_H"
        return (
            f"// AUTO-GENERATED by transpiler.py\n"
            f"#ifndef {guard}\n"
            f"#define {guard}\n"
            f'#include "ap_fixed.h"\n\n'
            f"{self.return_type} {self.func_name}({params});\n\n"
            f"#endif\n"
        )


# ---------------------------------------------------------------------- #
# convenience wrappers
# ---------------------------------------------------------------------- #
def transpile(source, fixed_type="ap_fixed<16,6>", return_type=None):
    """Transpile Python source text. Returns (cpp_code, header_code)."""
    return HLSTranspiler(fixed_type=fixed_type, return_type=return_type).transpile(source)


def transpile_function(func, fixed_type="ap_fixed<16,6>", return_type=None):
    """Transpile a live Python function object (uses its source)."""
    src = textwrap.dedent(inspect.getsource(func))
    return transpile(src, fixed_type=fixed_type, return_type=return_type)


if __name__ == "__main__":
    import sys
    if len(sys.argv) < 2:
        print("usage: python transpiler.py <input.py> [return_type]")
        sys.exit(1)
    with open(sys.argv[1]) as f:
        src = f.read()
    rt = sys.argv[2] if len(sys.argv) > 2 else None
    cpp, hdr = transpile(src, return_type=rt)
    print(cpp)
